### ISSUE TITLE
Update pioneer based on WG change and LockID change

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3889]
## Context

LockId and WG names were changed and merged to Runtime mainnet branch, before the release Pioneer has to do the respective changes

- https://github.com/Joystream/joystream/pull/4388

## Scope
- [x] Changes  for lock id
- [x] Changes for WG name

⚠️ SHOULD BE MERGED ON MAINNET

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203438066757237) by [Unito](https://www.unito.io)

## QA
This should be tested on https://34.230.5.182.nip.io/network/config.json
Steps:
- Apply to an opening
- Check that the lock applies

**Comment by ivanturlakov** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/
wss://34.230.5.182.nip.io/ws-rpc

Trying to **Create App Working Group Lead Opening** proposal
⚠️ Selected App WG when creating, but got Forum WG
https://pioneer-2-git-mainnet-joystream.vercel.app/#/proposals/preview/39

**Comment by thesan** [comment]
@ivanturlakov thanks.

It looks like pioneer sent `Forum` as the group. Here's the [extrinsic call](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F34.230.5.182.nip.io%2Fws-rpc#/extrinsics/decode/0x010008160e1a000000000000002822a3731311212f20f161a7f39981ec0a5c6abc21f6e5cf505977299aa96d5f20001a000000000000008443726561746520576f726b696e672047726f7570204c656164204f70656e696e67942a2a43726561746520576f726b696e672047726f7570204c656164204f70656e696e672a2a012822a3731311212f20f161a7f39981ec0a5c6abc21f6e5cf505977299aa96d5f0004f5020a2143726561746520576f726b696e672047726f7570204c656164204f70656e696e6712252a2a43726561746520576f726b696e672047726f7570204c656164204f70656e696e672a2a18012a252a2a43726561746520576f726b696e672047726f7570204c656164204f70656e696e672a2a32250a2143726561746520576f726b696e672047726f7570204c656164204f70656e696e6710013a2143726561746520576f726b696e672047726f7570204c656164204f70656e696e6700a48966291000000000000000000000786804000100e40b5402000000000000000000000000):

```yml
proposalDetails: PalletProposalsCodexProposalDetails
{
  CreateWorkingGroupLeadOpening: {
    description: 0x0a2143726561746520576f726b696e672047726f7570204c656164204f70656e696e6712252a2a43726561746520576f726b696e672047726f7570204c656164204f70656e696e672a2a18012a252a2a43726561746520576f726b696e672047726f7570204c656164204f70656e696e672a2a32250a2143726561746520576f726b696e672047726f7570204c656164204f70656e696e6710013a2143726561746520576f726b696e672047726f7570204c656164204f70656e696e67
    stakePolicy: {
      stakeAmount: 17,770,000,000,000
      leavingUnstakingPeriod: 288,888
    }
    rewardPerBlock: 10,000,000,000
    group: Forum
  }
}
```

I'll check what happened
